version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8050:8050" # Dash працює на порту 8050
    volumes:
      - .:/app
    environment:
      - ENV=development
      - PYTHONPATH=/app:/app/src
    command: poetry run python src/evaluation.py
