version: "3.8"

services:
  dash-app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ../:/app
    environment:
      - DASH_DEBUG=true
