version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000" # Вказано для можливого розширення функціоналу
    volumes:
      - .:/app
    environment:
      - ENV=development
