# Використовуємо офіційний Python-образ
FROM python:3.10-slim

# Встановлюємо необхідні пакети Poetry
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Встановлюємо Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо файли конфігурації Poetry
COPY pyproject.toml poetry.lock ./

# Встановлюємо залежності проекту
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Копіюємо решту файлів проекту
COPY . .

# Визначаємо порт для Dash
EXPOSE 8050

# Вказуємо команду запуску evaluation.py
CMD ["poetry", "run", "python", "src/evaluation.py"]
